ALTER TABLE `alerts` ADD CONSTRAINT `alerts_employeeId_employees_id_fk` FOREIGN KEY (`employeeId`) REFERENCES `employees`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `alerts` ADD CONSTRAINT `alerts_vacationCycleId_vacation_cycles_id_fk` FOREIGN KEY (`vacationCycleId`) REFERENCES `vacation_cycles`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `alerts` ADD CONSTRAINT `alerts_vacationPeriodId_vacation_periods_id_fk` FOREIGN KEY (`vacationPeriodId`) REFERENCES `vacation_periods`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `alerts` ADD CONSTRAINT `alerts_handledByUserId_users_id_fk` FOREIGN KEY (`handledByUserId`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `approval_history` ADD CONSTRAINT `approval_history_vacationPeriodId_vacation_periods_id_fk` FOREIGN KEY (`vacationPeriodId`) REFERENCES `vacation_periods`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `approval_history` ADD CONSTRAINT `approval_history_changedByUserId_users_id_fk` FOREIGN KEY (`changedByUserId`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `audit_logs` ADD CONSTRAINT `audit_logs_actorUserId_users_id_fk` FOREIGN KEY (`actorUserId`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `employees` ADD CONSTRAINT `employees_jobRoleId_job_roles_id_fk` FOREIGN KEY (`jobRoleId`) REFERENCES `job_roles`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `employees` ADD CONSTRAINT `employees_operationalGroupId_operational_groups_id_fk` FOREIGN KEY (`operationalGroupId`) REFERENCES `operational_groups`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `employees` ADD CONSTRAINT `employees_baseId_bases_id_fk` FOREIGN KEY (`baseId`) REFERENCES `bases`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `operational_restrictions` ADD CONSTRAINT `operational_restrictions_operationalGroupId_operational_groups_id_fk` FOREIGN KEY (`operationalGroupId`) REFERENCES `operational_groups`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `operational_restrictions` ADD CONSTRAINT `operational_restrictions_jobRoleId_job_roles_id_fk` FOREIGN KEY (`jobRoleId`) REFERENCES `job_roles`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `operational_restrictions` ADD CONSTRAINT `operational_restrictions_baseId_bases_id_fk` FOREIGN KEY (`baseId`) REFERENCES `bases`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `vacation_cycles` ADD CONSTRAINT `vacation_cycles_employeeId_employees_id_fk` FOREIGN KEY (`employeeId`) REFERENCES `employees`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `vacation_periods` ADD CONSTRAINT `vacation_periods_employeeId_employees_id_fk` FOREIGN KEY (`employeeId`) REFERENCES `employees`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `vacation_periods` ADD CONSTRAINT `vacation_periods_vacationCycleId_vacation_cycles_id_fk` FOREIGN KEY (`vacationCycleId`) REFERENCES `vacation_cycles`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `vacation_periods` ADD CONSTRAINT `vacation_periods_requestedByUserId_users_id_fk` FOREIGN KEY (`requestedByUserId`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `vacation_periods` ADD CONSTRAINT `vacation_periods_approvedByUserId_users_id_fk` FOREIGN KEY (`approvedByUserId`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action;