import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { BellRing, CheckCircle2, CircleAlert, FilterX, Play, ShieldCheck } from "lucide-react";
import { useMemo, useState } from "react";

type AlertStatus = "open" | "acknowledged" | "resolved" | "dismissed";
type AlertSeverity = "info" | "warning" | "high" | "critical";
type AlertCategory = "expiration_soon" | "expiration_overdue" | "pending_request" | "negative_balance" | "conflict" | "data_quality" | "job_failure";
type AlertFilterState = { status: string; category: string; severity: string; startDate: string; endDate: string; employeeId: string; jobRoleId: string; operationalGroupId: string; baseId: string };

const statusLabels: Record<AlertStatus, string> = { open: "Em aberto", acknowledged: "Em tratativa", resolved: "Resolvido", dismissed: "Dispensado" };
const categoryLabels: Record<AlertCategory, string> = { expiration_soon: "Vencimento próximo", expiration_overdue: "Férias vencidas", pending_request: "Solicitação pendente", negative_balance: "Saldo negativo", conflict: "Conflito de ausência", data_quality: "Qualidade de dados", job_failure: "Falha de rotina" };
const severityLabels: Record<AlertSeverity, string> = { info: "Informação", warning: "Atenção", high: "Alta", critical: "Crítica" };
const severityStyles: Record<AlertSeverity, string> = { info: "bg-[#edf0ec] text-[#536159]", warning: "bg-[#f7efd8] text-[#85601d]", high: "bg-[#f9e5df] text-[#9d4737]", critical: "bg-[#f4d4cc] text-[#813527]" };

const emptyFilters: AlertFilterState = { status: "", category: "", severity: "", startDate: "", endDate: "", employeeId: "", jobRoleId: "", operationalGroupId: "", baseId: "" };

function formatDate(value: Date | string) { return new Intl.DateTimeFormat("pt-BR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }

export default function AlertsPage() {
  const { user } = useAuth();
  const utils = trpc.useUtils();
  const [filters, setFilters] = useState(emptyFilters);
  const alertFilters = useMemo(() => ({ status: (filters.status || undefined) as AlertStatus | undefined, category: (filters.category || undefined) as AlertCategory | undefined, severity: (filters.severity || undefined) as AlertSeverity | undefined, startDate: filters.startDate || undefined, endDate: filters.endDate || undefined, employeeId: filters.employeeId ? Number(filters.employeeId) : undefined, jobRoleId: filters.jobRoleId ? Number(filters.jobRoleId) : undefined, operationalGroupId: filters.operationalGroupId ? Number(filters.operationalGroupId) : undefined, baseId: filters.baseId ? Number(filters.baseId) : undefined }), [filters]);
  const alertsQuery = trpc.alerts.list.useQuery(alertFilters);
  const employeesQuery = trpc.employees.list.useQuery();
  const rolesQuery = trpc.organization.list.useQuery("jobRole");
  const groupsQuery = trpc.organization.list.useQuery("operationalGroup");
  const basesQuery = trpc.organization.list.useQuery("base");
  const canHandle = user?.role === "planner" || user?.role === "approver" || user?.role === "admin";
  const isAdmin = user?.role === "admin";
  const handleAlert = trpc.alerts.handle.useMutation({ onSuccess: () => { utils.alerts.list.invalidate(); utils.dashboard.summary.invalidate(); } });
  const runCheck = trpc.automation.runDailyCheckNow.useMutation({ onSuccess: () => { utils.alerts.list.invalidate(); utils.dashboard.summary.invalidate(); utils.automation.recentExecutions.invalidate(); } });
  const scheduleQuery = trpc.automation.dailyCheckSchedule.useQuery(undefined, { enabled: isAdmin });
  const executionsQuery = trpc.automation.recentExecutions.useQuery(undefined, { enabled: isAdmin });
  const scheduleCheck = trpc.automation.scheduleDailyCheck.useMutation({ onSuccess: () => scheduleQuery.refetch() });
  const alerts = alertsQuery.data ?? [];
  const openAlerts = alerts.filter(alert => alert.status === "open");

  function resolveAlert(id: number) {
    const handlingNote = window.prompt("Descreva a resolução adotada:");
    if (!handlingNote?.trim()) return;
    handleAlert.mutate({ alertId: id, status: "resolved", handlingNote });
  }

  return (
    <div className="mx-auto max-w-[1280px]">
      <header className="flex flex-col gap-6 border-b border-[#dce1da] pb-7 xl:flex-row xl:items-end xl:justify-between">
        <div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#65766d]">Acompanhamento</p><h1 className="mt-3 font-display text-4xl leading-none text-[#173f35] sm:text-5xl">Alertas e tratativas</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#617067] sm:text-base">Centralize vencimentos, pendências, saldos negativos e conflitos. Cada tratativa fica vinculada à pessoa responsável.</p></div>
        {isAdmin && <div className="flex flex-col gap-3 sm:flex-row"><Button variant="outline" onClick={() => runCheck.mutate()} disabled={runCheck.isPending} className="h-11 rounded-xl border-[#b9c6ba] bg-white text-[#173f35] hover:bg-[#eef2ed]"><Play className="mr-2 h-4 w-4" />{runCheck.isPending ? "Verificando..." : "Executar agora"}</Button><Button onClick={() => scheduleCheck.mutate()} disabled={scheduleQuery.isLoading || scheduleCheck.isPending || Boolean(scheduleQuery.data?.scheduleCronTaskUid)} className="h-11 rounded-xl bg-[#173f35] text-white hover:bg-[#0f3027]">{scheduleQuery.data?.scheduleCronTaskUid ? "Rotina diária ativa" : "Ativar rotina diária"}</Button></div>}
      </header>
      {isAdmin && <section className="mt-6 rounded-2xl border border-[#dce1da] bg-[#f7faf6] px-5 py-4 text-sm leading-6 text-[#536159]"><strong className="text-[#173f35]">Verificação interna diária:</strong> {scheduleQuery.data?.scheduleCronTaskUid ? `agendada para ${scheduleQuery.data.cronExpression} (UTC).` : "poderá ser ativada após a publicação da aplicação. Até lá, utilize “Executar agora” para validação controlada."} <strong className="text-[#173f35]">E-mails:</strong> resumo semanal às segundas-feiras, às 08:00 no horário de Brasília; falhas técnicas críticas são comunicadas imediatamente.{scheduleCheck.isError && <span className="ml-2 text-[#a14332]">{scheduleCheck.error.message}</span>}</section>}
      <section className="mt-6 rounded-3xl border border-[#dce1da] bg-white p-5 shadow-[0_8px_24px_rgba(37,58,48,0.04)] sm:p-6"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3"><Filter label="Status"><select value={filters.status} onChange={event => setFilters(current => ({ ...current, status: event.target.value }))}><option value="">Todos</option>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Filter><Filter label="Categoria"><select value={filters.category} onChange={event => setFilters(current => ({ ...current, category: event.target.value }))}><option value="">Todas</option>{Object.entries(categoryLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Filter><Filter label="Severidade"><select value={filters.severity} onChange={event => setFilters(current => ({ ...current, severity: event.target.value }))}><option value="">Todas</option>{Object.entries(severityLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Filter><Filter label="Colaborador"><select value={filters.employeeId} onChange={event => setFilters(current => ({ ...current, employeeId: event.target.value }))}><option value="">Todos</option>{(employeesQuery.data ?? []).map(entry => <option key={entry.id} value={entry.id}>{entry.fullName}</option>)}</select></Filter><Filter label="Cargo"><select value={filters.jobRoleId} onChange={event => setFilters(current => ({ ...current, jobRoleId: event.target.value }))}><option value="">Todos</option>{(rolesQuery.data ?? []).map(entry => <option key={entry.id} value={entry.id}>{entry.name}</option>)}</select></Filter><Filter label="Grupo"><select value={filters.operationalGroupId} onChange={event => setFilters(current => ({ ...current, operationalGroupId: event.target.value }))}><option value="">Todos</option>{(groupsQuery.data ?? []).map(entry => <option key={entry.id} value={entry.id}>{entry.name}</option>)}</select></Filter><Filter label="Base"><select value={filters.baseId} onChange={event => setFilters(current => ({ ...current, baseId: event.target.value }))}><option value="">Todas</option>{(basesQuery.data ?? []).map(entry => <option key={entry.id} value={entry.id}>{entry.name}</option>)}</select></Filter><Filter label="Identificado a partir de"><input type="date" value={filters.startDate} onChange={event => setFilters(current => ({ ...current, startDate: event.target.value }))} /></Filter><Filter label="Até"><input type="date" value={filters.endDate} onChange={event => setFilters(current => ({ ...current, endDate: event.target.value }))} /></Filter></div><div className="mt-5 flex justify-end border-t border-[#edf0ec] pt-4"><Button variant="outline" onClick={() => setFilters(emptyFilters)} className="rounded-xl border-[#cfd8d0] text-[#315f4d] hover:bg-[#eef2ed]"><FilterX className="mr-2 h-4 w-4" />Limpar filtros</Button></div></section>
      <section className="mt-7 grid gap-4 sm:grid-cols-3"><Summary label="Alertas em aberto" value={openAlerts.length} icon={BellRing} tone="gold" /><Summary label="Necessitam tratativa" value={alerts.filter(alert => alert.status === "acknowledged").length} icon={ShieldCheck} tone="green" /><Summary label="Resolvidos" value={alerts.filter(alert => alert.status === "resolved").length} icon={CheckCircle2} tone="slate" /></section>
      <section className="mt-7 overflow-hidden rounded-3xl border border-[#dce1da] bg-white shadow-[0_8px_24px_rgba(37,58,48,0.04)]"><div className="border-b border-[#e3e8e2] px-6 py-5"><p className="text-xs font-semibold uppercase tracking-[0.13em] text-[#718078]">Fila consolidada</p><h2 className="mt-2 font-display text-3xl text-[#173f35]">Ocorrências identificadas</h2></div>{alertsQuery.isLoading ? <div className="space-y-3 p-6">{Array.from({ length: 5 }, (_, index) => <Skeleton key={index} className="h-24 w-full bg-[#edf2eb]" />)}</div> : alertsQuery.isError ? <div className="p-8 text-sm text-[#a14332]">Não foi possível carregar os alertas.</div> : alerts.length === 0 ? <div className="px-6 py-16 text-center"><span className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-[#e6eee5] text-[#23604b]"><ShieldCheck className="h-6 w-6" /></span><p className="mt-5 font-display text-2xl text-[#173f35]">Nenhum alerta encontrado.</p><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-[#66736c]">Ajuste os filtros ou execute a verificação manual depois de cadastrar ciclos e períodos.</p></div> : <div className="divide-y divide-[#edf0ec]">{alerts.map(alert => <article key={alert.id} className="p-5 sm:p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${severityStyles[alert.severity as AlertSeverity]}`}>{categoryLabels[alert.category as AlertCategory]}</span><span className="text-xs font-semibold uppercase tracking-wide text-[#718078]">{statusLabels[alert.status as AlertStatus]}</span></div><h3 className="mt-3 font-semibold text-[#173f35]">{alert.title}</h3><p className="mt-1 max-w-3xl text-sm leading-6 text-[#66736c]">{alert.description}</p><p className="mt-3 text-xs text-[#718078]">Identificado em {formatDate(alert.detectedAt)}{alert.employeeName ? ` · ${alert.employeeName}` : ""}</p>{alert.handlingNote && <p className="mt-3 rounded-xl bg-[#f5f7f3] px-3 py-2 text-sm text-[#536159]"><strong>Tratativa:</strong> {alert.handlingNote}</p>}</div>{canHandle && alert.status !== "resolved" && alert.status !== "dismissed" && <div className="flex shrink-0 flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => handleAlert.mutate({ alertId: alert.id, status: "acknowledged" })} disabled={handleAlert.isPending || alert.status === "acknowledged"} className="rounded-lg border-[#cfd8d0] text-[#315f4d] hover:bg-[#eef2ed]">Assumir</Button><Button size="sm" onClick={() => resolveAlert(alert.id)} disabled={handleAlert.isPending} className="rounded-lg bg-[#276246] text-white hover:bg-[#1d4e36]">Resolver</Button></div>}</div></article>)}</div>}</section>
      {isAdmin && <section className="mt-7 overflow-hidden rounded-3xl border border-[#dce1da] bg-white shadow-[0_8px_24px_rgba(37,58,48,0.04)]"><div className="border-b border-[#e3e8e2] px-6 py-5"><p className="text-xs font-semibold uppercase tracking-[0.13em] text-[#718078]">Auditoria da automação</p><h2 className="mt-2 font-display text-3xl text-[#173f35]">Últimas execuções</h2></div>{executionsQuery.isLoading ? <div className="space-y-3 p-6">{Array.from({ length: 3 }, (_, index) => <Skeleton key={index} className="h-12 w-full bg-[#edf2eb]" />)}</div> : executionsQuery.data?.length ? <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-[#fafbf9] text-xs font-semibold uppercase tracking-[0.11em] text-[#718078]"><tr><th className="px-6 py-3">Execução</th><th className="px-5 py-3">Início</th><th className="px-5 py-3">Duração</th><th className="px-5 py-3">Processados</th><th className="px-5 py-3">Alertas</th><th className="px-5 py-3">Status</th></tr></thead><tbody>{executionsQuery.data.map(execution => <tr key={execution.id} className="border-t border-[#edf0ec]"><td className="px-6 py-4 font-semibold text-[#173f35]">{execution.jobName}</td><td className="px-5 py-4 text-[#54635b]">{formatDate(execution.startedAt)}</td><td className="px-5 py-4 text-[#54635b]">{execution.durationMs === null ? "Em andamento" : `${execution.durationMs} ms`}</td><td className="px-5 py-4 text-[#54635b]">{execution.recordsProcessed}</td><td className="px-5 py-4 text-[#54635b]">{execution.alertsCreated} novos · {execution.alertsUpdated} atualizados</td><td className="px-5 py-4 text-[#54635b]">{execution.status}</td></tr>)}</tbody></table></div> : <div className="p-8 text-sm text-[#66736c]">Nenhuma execução registrada ainda.</div>}</section>}
      {runCheck.isError && <p className="mt-4 flex items-center gap-2 text-sm text-[#a14332]"><CircleAlert className="h-4 w-4" />{runCheck.error.message}</p>}
    </div>
  );
}

function Filter({ label, children }: { label: string; children: React.ReactNode }) { return <label className="text-sm font-semibold text-[#334c40]">{label}<span className="mt-2 block [&>input]:h-11 [&>input]:w-full [&>input]:rounded-xl [&>input]:border [&>input]:border-[#cfd8d0] [&>input]:bg-white [&>input]:px-3 [&>input]:font-normal [&>input]:outline-none [&>input]:ring-[#4d8768] [&>input:focus]:ring-2 [&>select]:h-11 [&>select]:w-full [&>select]:rounded-xl [&>select]:border [&>select]:border-[#cfd8d0] [&>select]:bg-white [&>select]:px-3 [&>select]:font-normal [&>select]:outline-none [&>select]:ring-[#4d8768] [&>select:focus]:ring-2">{children}</span></label>; }

function Summary({ label, value, icon: Icon, tone }: { label: string; value: number; icon: typeof BellRing; tone: "gold" | "green" | "slate" }) { const tones = { gold: "bg-[#f7efd8] text-[#85601d]", green: "bg-[#e6eee5] text-[#23604b]", slate: "bg-[#edf0ec] text-[#536159]" }; return <article className="rounded-3xl border border-[#dce1da] bg-white p-5 shadow-[0_8px_24px_rgba(37,58,48,0.04)]"><span className={`flex h-10 w-10 items-center justify-center rounded-xl ${tones[tone]}`}><Icon className="h-5 w-5" /></span><p className="mt-5 text-xs font-semibold uppercase tracking-[0.13em] text-[#718078]">{label}</p><p className="mt-2 font-display text-4xl text-[#173f35]">{value}</p></article>; }
