import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, Mail, Send, UserPlus, XCircle } from "lucide-react";
import { FormEvent, useState } from "react";

function formatDateTime(value: Date | string | null) { return value ? new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(new Date(value)) : "—"; }

export default function EmailNotificationsPage() {
  const { user } = useAuth();
  const utils = trpc.useUtils();
  const [email, setEmail] = useState("");
  const [name, setName] = useState("");
  const configuration = trpc.emailNotifications.configuration.useQuery(undefined, { enabled: user?.role === "admin" });
  const addRecipient = trpc.emailNotifications.addRecipient.useMutation({ onSuccess: async () => { await utils.emailNotifications.configuration.invalidate(); setEmail(""); setName(""); } });
  const updateStatus = trpc.emailNotifications.setRecipientStatus.useMutation({ onSuccess: () => utils.emailNotifications.configuration.invalidate() });
  const sendTest = trpc.emailNotifications.sendTest.useMutation({ onSuccess: () => utils.emailNotifications.configuration.invalidate() });
  const isAdmin = user?.role === "admin";
  const data = configuration.data;
  function add(event: FormEvent<HTMLFormElement>) { event.preventDefault(); addRecipient.mutate({ email, name: name || undefined }); }

  if (!isAdmin) return <div className="mx-auto max-w-3xl rounded-3xl border border-[#e9d5a1] bg-[#fff9e7] p-7 text-[#6e5721]"><h1 className="font-display text-3xl">Notificações por e-mail</h1><p className="mt-3">A configuração de destinatários e testes do canal é limitada ao perfil de administração.</p></div>;

  return <div className="mx-auto max-w-[1180px]">
    <header className="border-b border-[#dce1da] pb-7"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#65766d]">Comunicação operacional</p><h1 className="mt-3 font-display text-4xl leading-none text-[#173f35] sm:text-5xl">Notificações por e-mail</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#617067] sm:text-base">Destinatários ativos recebem um resumo semanal com vencimentos, pendências, saldos negativos, conflitos e inconsistências. Falhas técnicas da rotina continuam sendo notificadas imediatamente. Cada envio fica registrado para auditoria.</p></header>
    {configuration.isLoading ? <div className="mt-7 grid gap-6 lg:grid-cols-2"><Skeleton className="h-80 rounded-3xl bg-[#e9eee8]" /><Skeleton className="h-80 rounded-3xl bg-[#e9eee8]" /></div> : <>
      <section className="mt-7 grid gap-6 lg:grid-cols-[1.1fr_0.9fr]"><div className="rounded-3xl border border-[#dce1da] bg-white p-6 shadow-[0_8px_24px_rgba(37,58,48,0.04)]"><div className="flex items-start gap-3"><div className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${data?.configured ? "bg-[#e6eee5] text-[#276246]" : "bg-[#f9e5df] text-[#9d4737]"}`}>{data?.configured ? <CheckCircle2 className="h-5 w-5" /> : <XCircle className="h-5 w-5" />}</div><div><p className="text-xs font-semibold uppercase tracking-[0.13em] text-[#718078]">Canal transacional</p><h2 className="mt-1 font-display text-2xl text-[#173f35]">{data?.configured ? "Resend configurado" : "Configuração pendente"}</h2><p className="mt-2 text-sm leading-6 text-[#66736c]">{data?.configured ? "O remetente verificado está disponível no servidor. Cadastre um destinatário e envie um teste antes do próximo resumo semanal." : "Inclua a chave do Resend e um remetente verificado nos segredos do projeto antes de ativar os envios."}</p></div></div><form onSubmit={add} className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="Nome (opcional)"><input value={name} onChange={event => setName(event.target.value)} placeholder="Ex.: RH" /></Field><Field label="E-mail"><input required type="email" value={email} onChange={event => setEmail(event.target.value)} placeholder="rh@empresa.com" /></Field><div className="sm:col-span-2"><Button type="submit" disabled={addRecipient.isPending || !data?.configured} className="h-11 w-full rounded-xl bg-[#173f35] text-white hover:bg-[#0f3027]"><UserPlus className="mr-2 h-4 w-4" />{addRecipient.isPending ? "Adicionando..." : "Adicionar destinatário"}</Button></div></form>{addRecipient.error && <p role="alert" className="mt-4 text-sm text-[#a14332]">{addRecipient.error.message}</p>}</div>
      <div className="rounded-3xl border border-[#dce1da] bg-[#173f35] p-6 text-white shadow-[0_8px_24px_rgba(37,58,48,0.08)]"><Mail className="h-6 w-6 text-[#e8d8a9]" /><p className="mt-6 text-xs font-semibold uppercase tracking-[0.13em] text-[#b6cbbd]">Política de envio</p><h2 className="mt-2 font-display text-3xl">Resumo às segundas, 08:00.</h2><p className="mt-3 text-sm leading-6 text-[#d6e4d4]">A verificação interna roda diariamente, mas o resumo de alertas é enviado uma vez por semana. A chave de idempotência impede repetição para o mesmo destinatário na mesma semana.</p><div className="mt-6 rounded-2xl border border-white/10 bg-white/[0.06] p-4 text-sm leading-6 text-[#d6e4d4]">O teste valida o remetente, a chave e a entrega pelo Resend. Falhas técnicas críticas da rotina permanecem imediatas.</div></div></section>
      <section className="mt-7 overflow-hidden rounded-3xl border border-[#dce1da] bg-white shadow-[0_8px_24px_rgba(37,58,48,0.04)]"><div className="border-b border-[#e3e8e2] px-6 py-5"><p className="text-xs font-semibold uppercase tracking-[0.13em] text-[#718078]">Destinatários</p><h2 className="mt-2 font-display text-3xl text-[#173f35]">Quem recebe os alertas</h2></div>{data?.recipients.length ? <div className="divide-y divide-[#edf0ec]">{data.recipients.map(recipient => <div key={recipient.id} className="flex flex-col gap-4 px-6 py-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold text-[#173f35]">{recipient.name || recipient.email}</p><p className="mt-1 text-sm text-[#66736c]">{recipient.name ? recipient.email : "Sem nome complementar"}</p></div><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${recipient.active ? "bg-[#e6eee5] text-[#23604b]" : "bg-[#f2f3f1] text-[#65766d]"}`}>{recipient.active ? "Ativo" : "Pausado"}</span><Button size="sm" variant="outline" disabled={sendTest.isPending || !recipient.active || !data.configured} onClick={() => sendTest.mutate({ recipientId: recipient.id })} className="rounded-lg border-[#cfd8d0] text-[#315f4d] hover:bg-[#eef2ed]"><Send className="mr-1 h-3.5 w-3.5" />Testar</Button><Button size="sm" variant="outline" disabled={updateStatus.isPending} onClick={() => updateStatus.mutate({ recipientId: recipient.id, active: !recipient.active })} className="rounded-lg border-[#cfd8d0] text-[#315f4d] hover:bg-[#eef2ed]">{recipient.active ? "Pausar" : "Ativar"}</Button></div></div>)}</div> : <div className="px-6 py-16 text-center"><Mail className="mx-auto h-7 w-7 text-[#65766d]" /><p className="mt-4 font-display text-2xl text-[#173f35]">Nenhum destinatário cadastrado.</p><p className="mt-2 text-sm text-[#66736c]">Adicione o primeiro e-mail para liberar o teste do canal.</p></div>}</section>
      <section className="mt-7 overflow-hidden rounded-3xl border border-[#dce1da] bg-white shadow-[0_8px_24px_rgba(37,58,48,0.04)]"><div className="border-b border-[#e3e8e2] px-6 py-5"><p className="text-xs font-semibold uppercase tracking-[0.13em] text-[#718078]">Auditoria de entrega</p><h2 className="mt-2 font-display text-3xl text-[#173f35]">Últimos e-mails</h2></div>{data?.deliveries.length ? <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-[#fafbf9] text-xs font-semibold uppercase tracking-[0.11em] text-[#718078]"><tr><th className="px-6 py-3">Destinatário</th><th className="px-5 py-3">Assunto</th><th className="px-5 py-3">Tipo</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Data</th></tr></thead><tbody>{data.deliveries.map(delivery => <tr key={delivery.id} className="border-t border-[#edf0ec]"><td className="px-6 py-4 text-[#54635b]">{delivery.recipientName || delivery.recipientEmail}</td><td className="px-5 py-4 font-semibold text-[#173f35]">{delivery.subject}</td><td className="px-5 py-4 text-[#54635b]">{delivery.notificationType === "test" ? "Teste" : delivery.notificationType === "weekly_summary" ? "Resumo semanal" : "Alerta crítico"}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${delivery.status === "sent" ? "bg-[#e6eee5] text-[#23604b]" : delivery.status === "failed" ? "bg-[#f9e5df] text-[#9d4737]" : "bg-[#f2f3f1] text-[#65766d]"}`}>{delivery.status === "sent" ? "Enviado" : delivery.status === "failed" ? "Falhou" : delivery.status}</span></td><td className="px-5 py-4 text-[#54635b]">{formatDateTime(delivery.sentAt || delivery.createdAt)}</td></tr>)}</tbody></table></div> : <p className="px-6 py-12 text-center text-sm text-[#66736c]">Nenhum envio registrado.</p>}</section>
    </>}
  </div>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="text-sm font-semibold text-[#334c40]">{label}<span className="mt-2 block [&>input]:h-11 [&>input]:w-full [&>input]:rounded-xl [&>input]:border [&>input]:border-[#cfd8d0] [&>input]:px-3 [&>input]:font-normal [&>input]:outline-none [&>input]:ring-[#4d8768] [&>input:focus]:ring-2">{children}</span></label>; }
