import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { guideModules, roleGuidance, statusGuide } from "@/lib/guideContent";
import { BookOpenCheck, CircleCheck, Clock3, Lightbulb, ShieldCheck, Sparkles } from "lucide-react";

export default function GuidePage() {
  return <div className="mx-auto max-w-[1180px] pb-10">
    <header className="relative overflow-hidden rounded-[2rem] border border-[#cbd9cf] bg-[#e9f0e9] px-6 py-9 sm:px-10 sm:py-12">
      <div className="absolute -right-8 -top-8 h-40 w-40 rounded-full bg-[#e8d8a9]/55 blur-3xl" />
      <div className="relative max-w-3xl"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.16em] text-[#567263]"><BookOpenCheck className="h-4 w-4" />Guia de uso</div><h1 className="mt-4 font-display text-4xl leading-[0.96] text-[#173f35] sm:text-6xl">Planeje com segurança. <span className="text-[#49735e]">Decida com clareza.</span></h1><p className="mt-5 text-sm leading-6 text-[#50645a] sm:text-base">Este guia apresenta o caminho recomendado para usar o sistema de Férias, desde o cadastro e o planejamento até a aprovação, os alertas e a importação de dados.</p></div>
    </header>

    <section className="mt-8 grid gap-4 md:grid-cols-3" aria-label="Primeiros passos">
      {[{ number: "01", title: "Confira seu acesso", description: "Identifique seu perfil e os módulos liberados para sua atuação." }, { number: "02", title: "Organize os dados", description: "Mantenha equipe, cargos, grupos e bases atualizados antes de planejar." }, { number: "03", title: "Acompanhe decisões", description: "Use calendário e alertas para agir antes de ocorrer um conflito." }].map(step => <Card key={step.number} className="border-[#dce1da] bg-white shadow-[0_8px_24px_rgba(37,58,48,0.04)]"><CardContent className="p-5"><span className="font-display text-3xl text-[#c39c44]">{step.number}</span><h2 className="mt-4 font-display text-2xl text-[#173f35]">{step.title}</h2><p className="mt-2 text-sm leading-6 text-[#617067]">{step.description}</p></CardContent></Card>)}</section>

    <section className="mt-10 grid gap-8 lg:grid-cols-[minmax(0,1.6fr)_minmax(280px,0.8fr)]">
      <div><div className="flex items-end justify-between gap-4 border-b border-[#dce1da] pb-4"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#65766d]">Passo a passo</p><h2 className="mt-2 font-display text-3xl text-[#173f35]">Como trabalhar no sistema</h2></div><Badge className="hidden rounded-full bg-[#e4eee6] px-3 py-1 text-[#315f4d] sm:inline-flex">8 orientações</Badge></div><Accordion type="single" collapsible className="mt-3">{guideModules.map((module, index) => <AccordionItem key={module.title} value={`module-${index}`} className="border-[#dce1da]"><AccordionTrigger className="py-5 text-left font-display text-xl text-[#173f35] hover:no-underline">{module.title}</AccordionTrigger><AccordionContent className="pb-5"><p className="text-sm leading-6 text-[#617067]">{module.description}</p><div className="mt-4 rounded-xl bg-[#f1f5f0] p-4"><p className="flex items-center gap-2 text-sm font-semibold text-[#315f4d]"><CircleCheck className="h-4 w-4" />Ação recomendada</p><p className="mt-1 text-sm leading-6 text-[#516359]">{module.action}</p></div></AccordionContent></AccordionItem>)}</Accordion></div>
      <aside className="space-y-5"><Card className="border-[#d5dfd4] bg-[#173f35] text-white shadow-[0_14px_30px_rgba(23,63,53,0.16)]"><CardContent className="p-6"><ShieldCheck className="h-6 w-6 text-[#e8d8a9]" /><h2 className="mt-4 font-display text-3xl">Regra de ouro</h2><p className="mt-3 text-sm leading-6 text-[#d6e4d4]">Nunca publique uma importação ou vincule uma pendência sem conferir a pessoa, as datas e o ciclo. A trilha de auditoria existe para preservar decisões justificadas.</p></CardContent></Card><Card className="border-[#ead9a3] bg-[#fff9e8]"><CardContent className="p-6"><Lightbulb className="h-5 w-5 text-[#a77c23]" /><h2 className="mt-3 font-display text-2xl text-[#664e19]">Quando pedir apoio</h2><p className="mt-2 text-sm leading-6 text-[#786735]">Solicite apoio à Administração se houver dados cadastrais incompletos, ciclo ausente, conflito de cobertura ou dúvida sobre permissões.</p></CardContent></Card></aside>
    </section>

    <section className="mt-10 grid gap-7 lg:grid-cols-2"><div className="rounded-3xl border border-[#dce1da] bg-white p-6"><div className="flex items-center gap-2 text-[#315f4d]"><Sparkles className="h-5 w-5" /><p className="text-xs font-semibold uppercase tracking-[0.14em]">Perfis de acesso</p></div><h2 className="mt-3 font-display text-3xl text-[#173f35]">O que cada perfil faz</h2><div className="mt-5 space-y-4">{roleGuidance.map(item => <div key={item.role} className="rounded-2xl bg-[#f3f6f2] p-4"><p className="font-semibold text-[#173f35]">{item.role}</p><p className="mt-1 text-sm leading-6 text-[#617067]">{item.description}</p></div>)}</div></div><div className="rounded-3xl border border-[#dce1da] bg-white p-6"><div className="flex items-center gap-2 text-[#315f4d]"><Clock3 className="h-5 w-5" /><p className="text-xs font-semibold uppercase tracking-[0.14em]">Glossário</p></div><h2 className="mt-3 font-display text-3xl text-[#173f35]">Estados de um período</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{statusGuide.map(item => <div key={item.label} className="rounded-2xl border border-[#e1e7e0] p-4"><p className="font-semibold text-[#315f4d]">{item.label}</p><p className="mt-1 text-sm leading-6 text-[#617067]">{item.description}</p></div>)}</div></div></section>
  </div>;
}
